/// The three build-stamp variables `native::version` reads through
/// `option_env!`, in the order they appear on the About screen.
const STAMP_VARS: [&str; 3] = [
    "AGENTO_BUILD_VERSION",
    "AGENTO_BUILD_COMMIT",
    "AGENTO_BUILD_DATE",
];

/// The commands `lib.rs` registers through `tauri::generate_handler!`, which is
/// the list this build script generates `allow-*`/`deny-*` permissions for.
///
/// **It must stay in step with `generate_handler!` and with the `allow-*`
/// entries in `capabilities/default.json`, and a drift is silent in dev and
/// fatal in the installer** — which is why
/// `app_commands_capability_and_handler_agree` (`src/lib.rs`) asserts all three
/// against each other rather than trusting a comment. See `app_manifest` below
/// for why the ACL reaches these at all.
const APP_COMMANDS: &[&str] = &["host_info", "log_files", "read_log", "export_logs"];

fn main() {
    stamp_build_info();
    app_manifest()
}

/// Generate an ACL permission per app command, so the shipped build can call
/// its own `#[tauri::command]`s at all.
///
/// **`invoke_handler` commands do not bypass the ACL.** `CLAUDE.md` said they
/// did until #401, and that wrong conclusion is what let a release ship where
/// every one of them was refused. Tauri gates app and plugin commands on the
/// same condition (`tauri 2.11.5`, `src/webview/mod.rs:1820`):
///
/// ```text
/// if (plugin_command.is_some() || has_app_acl_manifest || !is_local)
///   && … && invoke.acl.is_none() { reject("Command … not allowed by ACL") }
/// ```
///
/// `lib.rs` navigates the release window to `http://127.0.0.1:<port>` so the UI
/// is same-origin with the API, and `Webview::is_local_url` counts only
/// `tauri://localhost`, the configured `devUrl`/`frontendDist` or a registered
/// custom protocol as local — so `is_local` is **false** in every shipped
/// build, `invoke.acl` resolved to `None` with no app manifest to resolve
/// against, and Settings → Logs answered `Command log_files not allowed by ACL`
/// while `host_info` failed silently (`useHostInfo` swallows it), taking the
/// "Claude Code CLI not found" banner with it. Dev never saw it: `devUrl` *is*
/// the local origin, so the whole class is invisible under `npm run app`.
///
/// `commands` autogenerates one `allow-<kebab>`/`deny-<kebab>` pair per entry
/// into `permissions/autogenerated/` (committed, so a fresh checkout does not
/// go dirty on its first build); `capabilities/default.json` then grants the
/// four `allow-*`. App-scoped identifiers carry no prefix, because
/// `tauri-build`'s `acl.rs` resolves them under `APP_ACL_KEY`.
///
/// One consequence is deliberate and worth keeping: an app manifest makes
/// `has_app_acl_manifest` true, so the ACL is now enforced for the **local**
/// origin too. The next command added without a capability entry therefore
/// breaks under `npm run app` instead of only in the installer.
fn app_manifest() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

/// Forward the release workflow's build stamp into the crate, and make cargo
/// notice when it moves.
///
/// `native::version` reads these with `option_env!`, which is resolved at
/// compile time — so an unstamped build answers `GET /api/version` with
/// `dev`/`unknown`/`unknown`, which is what every shipped release did until
/// this existed (the port kept the Go server's `-ldflags` hook and nothing ever
/// took over the stamping job).
///
/// **Passing the variables to `cargo build` is not enough on its own**, and
/// that is the whole reason this indirection exists rather than the workflow
/// simply exporting them. The release job restores a `Swatinem/rust-cache`
/// target directory from an earlier tag's run, so a rebuild has to be
/// *invalidated* by the new value or the previous release's stamp is what
/// ships. `rerun-if-env-changed` re-runs this script when a value moves, and
/// re-emitting the value as `rustc-env` is what then forces the crate itself to
/// recompile — a build script that only declared the dependency would rerun and
/// change nothing.
///
/// An unset variable emits nothing, so `option_env!` still answers `None` and a
/// local `npm run app:build` still reports itself as `dev`. That is deliberate:
/// an unstamped build is a development build, and claiming the version in
/// `tauri.conf.json` would make one indistinguishable from the release.
fn stamp_build_info() {
    for var in STAMP_VARS {
        println!("cargo:rerun-if-env-changed={var}");
        if let Ok(value) = std::env::var(var) {
            if !value.is_empty() {
                println!("cargo:rustc-env={var}={value}");
            }
        }
    }
}
