version: 2

project_name: agento

before:
  hooks:
    - sh -c "cd frontend && npm ci --legacy-peer-deps && npm run build"

builds:
  - id: agento
    main: .
    binary: agento
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/shaharia-lab/agento/internal/build.Version={{.Version}}
      - -X github.com/shaharia-lab/agento/internal/build.CommitSHA={{.Commit}}
      - -X github.com/shaharia-lab/agento/internal/build.BuildDate={{.Date}}

archives:
  - id: agento
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "Other Changes"
      order: 999

brews:
  - name: agento
    repository:
      owner: shaharia-lab
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/shaharia-lab/agento"
    description: "Agento — AI Agents Platform"
    license: "MIT"
    folder: Formula
    test: |
      system "#{bin}/agento", "--version"
    install: |
      bin.install "agento"

release:
  github:
    owner: shaharia-lab
    name: agento
  draft: false
  prerelease: auto
