// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pricing "github.com/shaharia-lab/agento/internal/pricing"
	mock "github.com/stretchr/testify/mock"

	service "github.com/shaharia-lab/agento/internal/service"

	time "time"
)

// MockPricingService is an autogenerated mock type for the PricingService type
type MockPricingService struct {
	mock.Mock
}

type MockPricingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricingService) EXPECT() *MockPricingService_Expecter {
	return &MockPricingService_Expecter{mock: &_m.Mock}
}

// AddRate provides a mock function with given fields: ctx, r
func (_m *MockPricingService) AddRate(ctx context.Context, r pricing.Rate) (*pricing.Rate, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for AddRate")
	}

	var r0 *pricing.Rate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pricing.Rate) (*pricing.Rate, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pricing.Rate) *pricing.Rate); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pricing.Rate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pricing.Rate) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingService_AddRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRate'
type MockPricingService_AddRate_Call struct {
	*mock.Call
}

// AddRate is a helper method to define mock.On call
//   - ctx context.Context
//   - r pricing.Rate
func (_e *MockPricingService_Expecter) AddRate(ctx interface{}, r interface{}) *MockPricingService_AddRate_Call {
	return &MockPricingService_AddRate_Call{Call: _e.mock.On("AddRate", ctx, r)}
}

func (_c *MockPricingService_AddRate_Call) Run(run func(ctx context.Context, r pricing.Rate)) *MockPricingService_AddRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pricing.Rate))
	})
	return _c
}

func (_c *MockPricingService_AddRate_Call) Return(_a0 *pricing.Rate, _a1 error) *MockPricingService_AddRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingService_AddRate_Call) RunAndReturn(run func(context.Context, pricing.Rate) (*pricing.Rate, error)) *MockPricingService_AddRate_Call {
	_c.Call.Return(run)
	return _c
}

// Catalog provides a mock function with given fields: ctx
func (_m *MockPricingService) Catalog(ctx context.Context) (*service.PricingCatalog, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Catalog")
	}

	var r0 *service.PricingCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.PricingCatalog, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.PricingCatalog); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PricingCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingService_Catalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Catalog'
type MockPricingService_Catalog_Call struct {
	*mock.Call
}

// Catalog is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPricingService_Expecter) Catalog(ctx interface{}) *MockPricingService_Catalog_Call {
	return &MockPricingService_Catalog_Call{Call: _e.mock.On("Catalog", ctx)}
}

func (_c *MockPricingService_Catalog_Call) Run(run func(ctx context.Context)) *MockPricingService_Catalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPricingService_Catalog_Call) Return(_a0 *service.PricingCatalog, _a1 error) *MockPricingService_Catalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingService_Catalog_Call) RunAndReturn(run func(context.Context) (*service.PricingCatalog, error)) *MockPricingService_Catalog_Call {
	_c.Call.Return(run)
	return _c
}

// CorrectRate provides a mock function with given fields: ctx, r
func (_m *MockPricingService) CorrectRate(ctx context.Context, r pricing.Rate) (*pricing.Rate, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CorrectRate")
	}

	var r0 *pricing.Rate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pricing.Rate) (*pricing.Rate, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pricing.Rate) *pricing.Rate); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pricing.Rate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pricing.Rate) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingService_CorrectRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CorrectRate'
type MockPricingService_CorrectRate_Call struct {
	*mock.Call
}

// CorrectRate is a helper method to define mock.On call
//   - ctx context.Context
//   - r pricing.Rate
func (_e *MockPricingService_Expecter) CorrectRate(ctx interface{}, r interface{}) *MockPricingService_CorrectRate_Call {
	return &MockPricingService_CorrectRate_Call{Call: _e.mock.On("CorrectRate", ctx, r)}
}

func (_c *MockPricingService_CorrectRate_Call) Run(run func(ctx context.Context, r pricing.Rate)) *MockPricingService_CorrectRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pricing.Rate))
	})
	return _c
}

func (_c *MockPricingService_CorrectRate_Call) Return(_a0 *pricing.Rate, _a1 error) *MockPricingService_CorrectRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingService_CorrectRate_Call) RunAndReturn(run func(context.Context, pricing.Rate) (*pricing.Rate, error)) *MockPricingService_CorrectRate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRate provides a mock function with given fields: ctx, modelPattern, effectiveFrom
func (_m *MockPricingService) DeleteRate(ctx context.Context, modelPattern string, effectiveFrom time.Time) error {
	ret := _m.Called(ctx, modelPattern, effectiveFrom)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, modelPattern, effectiveFrom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPricingService_DeleteRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRate'
type MockPricingService_DeleteRate_Call struct {
	*mock.Call
}

// DeleteRate is a helper method to define mock.On call
//   - ctx context.Context
//   - modelPattern string
//   - effectiveFrom time.Time
func (_e *MockPricingService_Expecter) DeleteRate(ctx interface{}, modelPattern interface{}, effectiveFrom interface{}) *MockPricingService_DeleteRate_Call {
	return &MockPricingService_DeleteRate_Call{Call: _e.mock.On("DeleteRate", ctx, modelPattern, effectiveFrom)}
}

func (_c *MockPricingService_DeleteRate_Call) Run(run func(ctx context.Context, modelPattern string, effectiveFrom time.Time)) *MockPricingService_DeleteRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockPricingService_DeleteRate_Call) Return(_a0 error) *MockPricingService_DeleteRate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPricingService_DeleteRate_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockPricingService_DeleteRate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPricingService creates a new instance of MockPricingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricingService {
	mock := &MockPricingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
