// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"

	service "github.com/shaharia-lab/agento/internal/service"
)

// MockTriggerService is an autogenerated mock type for the TriggerService type
type MockTriggerService struct {
	mock.Mock
}

type MockTriggerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTriggerService) EXPECT() *MockTriggerService_Expecter {
	return &MockTriggerService_Expecter{mock: &_m.Mock}
}

// CreateRule provides a mock function with given fields: ctx, rule
func (_m *MockTriggerService) CreateRule(ctx context.Context, rule *config.TriggerRule) (*config.TriggerRule, error) {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 *config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.TriggerRule) (*config.TriggerRule, error)); ok {
		return rf(ctx, rule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.TriggerRule) *config.TriggerRule); ok {
		r0 = rf(ctx, rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.TriggerRule) error); ok {
		r1 = rf(ctx, rule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerService_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockTriggerService_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *config.TriggerRule
func (_e *MockTriggerService_Expecter) CreateRule(ctx interface{}, rule interface{}) *MockTriggerService_CreateRule_Call {
	return &MockTriggerService_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, rule)}
}

func (_c *MockTriggerService_CreateRule_Call) Run(run func(ctx context.Context, rule *config.TriggerRule)) *MockTriggerService_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.TriggerRule))
	})
	return _c
}

func (_c *MockTriggerService_CreateRule_Call) Return(_a0 *config.TriggerRule, _a1 error) *MockTriggerService_CreateRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerService_CreateRule_Call) RunAndReturn(run func(context.Context, *config.TriggerRule) (*config.TriggerRule, error)) *MockTriggerService_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: ctx, id
func (_m *MockTriggerService) DeleteRule(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerService_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockTriggerService_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTriggerService_Expecter) DeleteRule(ctx interface{}, id interface{}) *MockTriggerService_DeleteRule_Call {
	return &MockTriggerService_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, id)}
}

func (_c *MockTriggerService_DeleteRule_Call) Run(run func(ctx context.Context, id string)) *MockTriggerService_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_DeleteRule_Call) Return(_a0 error) *MockTriggerService_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerService_DeleteRule_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerService_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebhook provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerService) DeleteWebhook(ctx context.Context, integrationID string) error {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, integrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerService_DeleteWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebhook'
type MockTriggerService_DeleteWebhook_Call struct {
	*mock.Call
}

// DeleteWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerService_Expecter) DeleteWebhook(ctx interface{}, integrationID interface{}) *MockTriggerService_DeleteWebhook_Call {
	return &MockTriggerService_DeleteWebhook_Call{Call: _e.mock.On("DeleteWebhook", ctx, integrationID)}
}

func (_c *MockTriggerService_DeleteWebhook_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerService_DeleteWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_DeleteWebhook_Call) Return(_a0 error) *MockTriggerService_DeleteWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerService_DeleteWebhook_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerService_DeleteWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function with given fields: ctx, id
func (_m *MockTriggerService) GetRule(ctx context.Context, id string) (*config.TriggerRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.TriggerRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.TriggerRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerService_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockTriggerService_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTriggerService_Expecter) GetRule(ctx interface{}, id interface{}) *MockTriggerService_GetRule_Call {
	return &MockTriggerService_GetRule_Call{Call: _e.mock.On("GetRule", ctx, id)}
}

func (_c *MockTriggerService_GetRule_Call) Run(run func(ctx context.Context, id string)) *MockTriggerService_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_GetRule_Call) Return(_a0 *config.TriggerRule, _a1 error) *MockTriggerService_GetRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerService_GetRule_Call) RunAndReturn(run func(context.Context, string) (*config.TriggerRule, error)) *MockTriggerService_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebhookStatus provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerService) GetWebhookStatus(ctx context.Context, integrationID string) (*service.WebhookStatus, error) {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookStatus")
	}

	var r0 *service.WebhookStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.WebhookStatus, error)); ok {
		return rf(ctx, integrationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.WebhookStatus); ok {
		r0 = rf(ctx, integrationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.WebhookStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, integrationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerService_GetWebhookStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebhookStatus'
type MockTriggerService_GetWebhookStatus_Call struct {
	*mock.Call
}

// GetWebhookStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerService_Expecter) GetWebhookStatus(ctx interface{}, integrationID interface{}) *MockTriggerService_GetWebhookStatus_Call {
	return &MockTriggerService_GetWebhookStatus_Call{Call: _e.mock.On("GetWebhookStatus", ctx, integrationID)}
}

func (_c *MockTriggerService_GetWebhookStatus_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerService_GetWebhookStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_GetWebhookStatus_Call) Return(_a0 *service.WebhookStatus, _a1 error) *MockTriggerService_GetWebhookStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerService_GetWebhookStatus_Call) RunAndReturn(run func(context.Context, string) (*service.WebhookStatus, error)) *MockTriggerService_GetWebhookStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListRules provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerService) ListRules(ctx context.Context, integrationID string) ([]*config.TriggerRule, error) {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 []*config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*config.TriggerRule, error)); ok {
		return rf(ctx, integrationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*config.TriggerRule); ok {
		r0 = rf(ctx, integrationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, integrationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerService_ListRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRules'
type MockTriggerService_ListRules_Call struct {
	*mock.Call
}

// ListRules is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerService_Expecter) ListRules(ctx interface{}, integrationID interface{}) *MockTriggerService_ListRules_Call {
	return &MockTriggerService_ListRules_Call{Call: _e.mock.On("ListRules", ctx, integrationID)}
}

func (_c *MockTriggerService_ListRules_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerService_ListRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_ListRules_Call) Return(_a0 []*config.TriggerRule, _a1 error) *MockTriggerService_ListRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerService_ListRules_Call) RunAndReturn(run func(context.Context, string) ([]*config.TriggerRule, error)) *MockTriggerService_ListRules_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateSecret provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerService) RegenerateSecret(ctx context.Context, integrationID string) error {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, integrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerService_RegenerateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateSecret'
type MockTriggerService_RegenerateSecret_Call struct {
	*mock.Call
}

// RegenerateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerService_Expecter) RegenerateSecret(ctx interface{}, integrationID interface{}) *MockTriggerService_RegenerateSecret_Call {
	return &MockTriggerService_RegenerateSecret_Call{Call: _e.mock.On("RegenerateSecret", ctx, integrationID)}
}

func (_c *MockTriggerService_RegenerateSecret_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerService_RegenerateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_RegenerateSecret_Call) Return(_a0 error) *MockTriggerService_RegenerateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerService_RegenerateSecret_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerService_RegenerateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterWebhook provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerService) RegisterWebhook(ctx context.Context, integrationID string) error {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, integrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerService_RegisterWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWebhook'
type MockTriggerService_RegisterWebhook_Call struct {
	*mock.Call
}

// RegisterWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerService_Expecter) RegisterWebhook(ctx interface{}, integrationID interface{}) *MockTriggerService_RegisterWebhook_Call {
	return &MockTriggerService_RegisterWebhook_Call{Call: _e.mock.On("RegisterWebhook", ctx, integrationID)}
}

func (_c *MockTriggerService_RegisterWebhook_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerService_RegisterWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerService_RegisterWebhook_Call) Return(_a0 error) *MockTriggerService_RegisterWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerService_RegisterWebhook_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerService_RegisterWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: ctx, id, rule
func (_m *MockTriggerService) UpdateRule(ctx context.Context, id string, rule *config.TriggerRule) (*config.TriggerRule, error) {
	ret := _m.Called(ctx, id, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 *config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.TriggerRule) (*config.TriggerRule, error)); ok {
		return rf(ctx, id, rule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *config.TriggerRule) *config.TriggerRule); ok {
		r0 = rf(ctx, id, rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *config.TriggerRule) error); ok {
		r1 = rf(ctx, id, rule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerService_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockTriggerService_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rule *config.TriggerRule
func (_e *MockTriggerService_Expecter) UpdateRule(ctx interface{}, id interface{}, rule interface{}) *MockTriggerService_UpdateRule_Call {
	return &MockTriggerService_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, id, rule)}
}

func (_c *MockTriggerService_UpdateRule_Call) Run(run func(ctx context.Context, id string, rule *config.TriggerRule)) *MockTriggerService_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*config.TriggerRule))
	})
	return _c
}

func (_c *MockTriggerService_UpdateRule_Call) Return(_a0 *config.TriggerRule, _a1 error) *MockTriggerService_UpdateRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerService_UpdateRule_Call) RunAndReturn(run func(context.Context, string, *config.TriggerRule) (*config.TriggerRule, error)) *MockTriggerService_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTriggerService creates a new instance of MockTriggerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTriggerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTriggerService {
	mock := &MockTriggerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
