// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shaharia-lab/agento/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// MockTriggerStore is an autogenerated mock type for the TriggerStore type
type MockTriggerStore struct {
	mock.Mock
}

type MockTriggerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTriggerStore) EXPECT() *MockTriggerStore_Expecter {
	return &MockTriggerStore_Expecter{mock: &_m.Mock}
}

// CreateRule provides a mock function with given fields: ctx, rule
func (_m *MockTriggerStore) CreateRule(ctx context.Context, rule *config.TriggerRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.TriggerRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockTriggerStore_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *config.TriggerRule
func (_e *MockTriggerStore_Expecter) CreateRule(ctx interface{}, rule interface{}) *MockTriggerStore_CreateRule_Call {
	return &MockTriggerStore_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, rule)}
}

func (_c *MockTriggerStore_CreateRule_Call) Run(run func(ctx context.Context, rule *config.TriggerRule)) *MockTriggerStore_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.TriggerRule))
	})
	return _c
}

func (_c *MockTriggerStore_CreateRule_Call) Return(_a0 error) *MockTriggerStore_CreateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_CreateRule_Call) RunAndReturn(run func(context.Context, *config.TriggerRule) error) *MockTriggerStore_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: ctx, id
func (_m *MockTriggerStore) DeleteRule(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockTriggerStore_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTriggerStore_Expecter) DeleteRule(ctx interface{}, id interface{}) *MockTriggerStore_DeleteRule_Call {
	return &MockTriggerStore_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, id)}
}

func (_c *MockTriggerStore_DeleteRule_Call) Run(run func(ctx context.Context, id string)) *MockTriggerStore_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerStore_DeleteRule_Call) Return(_a0 error) *MockTriggerStore_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_DeleteRule_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerStore_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRulesByIntegration provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerStore) DeleteRulesByIntegration(ctx context.Context, integrationID string) error {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRulesByIntegration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, integrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_DeleteRulesByIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRulesByIntegration'
type MockTriggerStore_DeleteRulesByIntegration_Call struct {
	*mock.Call
}

// DeleteRulesByIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerStore_Expecter) DeleteRulesByIntegration(ctx interface{}, integrationID interface{}) *MockTriggerStore_DeleteRulesByIntegration_Call {
	return &MockTriggerStore_DeleteRulesByIntegration_Call{Call: _e.mock.On("DeleteRulesByIntegration", ctx, integrationID)}
}

func (_c *MockTriggerStore_DeleteRulesByIntegration_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerStore_DeleteRulesByIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerStore_DeleteRulesByIntegration_Call) Return(_a0 error) *MockTriggerStore_DeleteRulesByIntegration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_DeleteRulesByIntegration_Call) RunAndReturn(run func(context.Context, string) error) *MockTriggerStore_DeleteRulesByIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function with given fields: ctx, id
func (_m *MockTriggerStore) GetRule(ctx context.Context, id string) (*config.TriggerRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*config.TriggerRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *config.TriggerRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerStore_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockTriggerStore_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTriggerStore_Expecter) GetRule(ctx interface{}, id interface{}) *MockTriggerStore_GetRule_Call {
	return &MockTriggerStore_GetRule_Call{Call: _e.mock.On("GetRule", ctx, id)}
}

func (_c *MockTriggerStore_GetRule_Call) Run(run func(ctx context.Context, id string)) *MockTriggerStore_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerStore_GetRule_Call) Return(_a0 *config.TriggerRule, _a1 error) *MockTriggerStore_GetRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerStore_GetRule_Call) RunAndReturn(run func(context.Context, string) (*config.TriggerRule, error)) *MockTriggerStore_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebhookInfo provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerStore) GetWebhookInfo(ctx context.Context, integrationID string) (string, string, string, error) {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookInfo")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, string, error)); ok {
		return rf(ctx, integrationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, integrationID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, integrationID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, integrationID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, integrationID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTriggerStore_GetWebhookInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebhookInfo'
type MockTriggerStore_GetWebhookInfo_Call struct {
	*mock.Call
}

// GetWebhookInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerStore_Expecter) GetWebhookInfo(ctx interface{}, integrationID interface{}) *MockTriggerStore_GetWebhookInfo_Call {
	return &MockTriggerStore_GetWebhookInfo_Call{Call: _e.mock.On("GetWebhookInfo", ctx, integrationID)}
}

func (_c *MockTriggerStore_GetWebhookInfo_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerStore_GetWebhookInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerStore_GetWebhookInfo_Call) Return(secret string, status string, webhookErr string, err error) *MockTriggerStore_GetWebhookInfo_Call {
	_c.Call.Return(secret, status, webhookErr, err)
	return _c
}

func (_c *MockTriggerStore_GetWebhookInfo_Call) RunAndReturn(run func(context.Context, string) (string, string, string, error)) *MockTriggerStore_GetWebhookInfo_Call {
	_c.Call.Return(run)
	return _c
}

// IsUpdateProcessed provides a mock function with given fields: ctx, integrationID, updateID
func (_m *MockTriggerStore) IsUpdateProcessed(ctx context.Context, integrationID string, updateID int64) (bool, error) {
	ret := _m.Called(ctx, integrationID, updateID)

	if len(ret) == 0 {
		panic("no return value specified for IsUpdateProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (bool, error)); ok {
		return rf(ctx, integrationID, updateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) bool); ok {
		r0 = rf(ctx, integrationID, updateID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, integrationID, updateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerStore_IsUpdateProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUpdateProcessed'
type MockTriggerStore_IsUpdateProcessed_Call struct {
	*mock.Call
}

// IsUpdateProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
//   - updateID int64
func (_e *MockTriggerStore_Expecter) IsUpdateProcessed(ctx interface{}, integrationID interface{}, updateID interface{}) *MockTriggerStore_IsUpdateProcessed_Call {
	return &MockTriggerStore_IsUpdateProcessed_Call{Call: _e.mock.On("IsUpdateProcessed", ctx, integrationID, updateID)}
}

func (_c *MockTriggerStore_IsUpdateProcessed_Call) Run(run func(ctx context.Context, integrationID string, updateID int64)) *MockTriggerStore_IsUpdateProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockTriggerStore_IsUpdateProcessed_Call) Return(_a0 bool, _a1 error) *MockTriggerStore_IsUpdateProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerStore_IsUpdateProcessed_Call) RunAndReturn(run func(context.Context, string, int64) (bool, error)) *MockTriggerStore_IsUpdateProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// ListRules provides a mock function with given fields: ctx, integrationID
func (_m *MockTriggerStore) ListRules(ctx context.Context, integrationID string) ([]*config.TriggerRule, error) {
	ret := _m.Called(ctx, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 []*config.TriggerRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*config.TriggerRule, error)); ok {
		return rf(ctx, integrationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*config.TriggerRule); ok {
		r0 = rf(ctx, integrationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*config.TriggerRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, integrationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTriggerStore_ListRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRules'
type MockTriggerStore_ListRules_Call struct {
	*mock.Call
}

// ListRules is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
func (_e *MockTriggerStore_Expecter) ListRules(ctx interface{}, integrationID interface{}) *MockTriggerStore_ListRules_Call {
	return &MockTriggerStore_ListRules_Call{Call: _e.mock.On("ListRules", ctx, integrationID)}
}

func (_c *MockTriggerStore_ListRules_Call) Run(run func(ctx context.Context, integrationID string)) *MockTriggerStore_ListRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTriggerStore_ListRules_Call) Return(_a0 []*config.TriggerRule, _a1 error) *MockTriggerStore_ListRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTriggerStore_ListRules_Call) RunAndReturn(run func(context.Context, string) ([]*config.TriggerRule, error)) *MockTriggerStore_ListRules_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUpdateProcessed provides a mock function with given fields: ctx, integrationID, updateID
func (_m *MockTriggerStore) MarkUpdateProcessed(ctx context.Context, integrationID string, updateID int64) error {
	ret := _m.Called(ctx, integrationID, updateID)

	if len(ret) == 0 {
		panic("no return value specified for MarkUpdateProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, integrationID, updateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_MarkUpdateProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUpdateProcessed'
type MockTriggerStore_MarkUpdateProcessed_Call struct {
	*mock.Call
}

// MarkUpdateProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
//   - updateID int64
func (_e *MockTriggerStore_Expecter) MarkUpdateProcessed(ctx interface{}, integrationID interface{}, updateID interface{}) *MockTriggerStore_MarkUpdateProcessed_Call {
	return &MockTriggerStore_MarkUpdateProcessed_Call{Call: _e.mock.On("MarkUpdateProcessed", ctx, integrationID, updateID)}
}

func (_c *MockTriggerStore_MarkUpdateProcessed_Call) Run(run func(ctx context.Context, integrationID string, updateID int64)) *MockTriggerStore_MarkUpdateProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockTriggerStore_MarkUpdateProcessed_Call) Return(_a0 error) *MockTriggerStore_MarkUpdateProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_MarkUpdateProcessed_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockTriggerStore_MarkUpdateProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// SetWebhookInfo provides a mock function with given fields: ctx, integrationID, secret, status, webhookErr
func (_m *MockTriggerStore) SetWebhookInfo(ctx context.Context, integrationID string, secret string, status string, webhookErr string) error {
	ret := _m.Called(ctx, integrationID, secret, status, webhookErr)

	if len(ret) == 0 {
		panic("no return value specified for SetWebhookInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, integrationID, secret, status, webhookErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_SetWebhookInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWebhookInfo'
type MockTriggerStore_SetWebhookInfo_Call struct {
	*mock.Call
}

// SetWebhookInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - integrationID string
//   - secret string
//   - status string
//   - webhookErr string
func (_e *MockTriggerStore_Expecter) SetWebhookInfo(ctx interface{}, integrationID interface{}, secret interface{}, status interface{}, webhookErr interface{}) *MockTriggerStore_SetWebhookInfo_Call {
	return &MockTriggerStore_SetWebhookInfo_Call{Call: _e.mock.On("SetWebhookInfo", ctx, integrationID, secret, status, webhookErr)}
}

func (_c *MockTriggerStore_SetWebhookInfo_Call) Run(run func(ctx context.Context, integrationID string, secret string, status string, webhookErr string)) *MockTriggerStore_SetWebhookInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTriggerStore_SetWebhookInfo_Call) Return(_a0 error) *MockTriggerStore_SetWebhookInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_SetWebhookInfo_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockTriggerStore_SetWebhookInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: ctx, rule
func (_m *MockTriggerStore) UpdateRule(ctx context.Context, rule *config.TriggerRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.TriggerRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTriggerStore_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockTriggerStore_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *config.TriggerRule
func (_e *MockTriggerStore_Expecter) UpdateRule(ctx interface{}, rule interface{}) *MockTriggerStore_UpdateRule_Call {
	return &MockTriggerStore_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, rule)}
}

func (_c *MockTriggerStore_UpdateRule_Call) Run(run func(ctx context.Context, rule *config.TriggerRule)) *MockTriggerStore_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.TriggerRule))
	})
	return _c
}

func (_c *MockTriggerStore_UpdateRule_Call) Return(_a0 error) *MockTriggerStore_UpdateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTriggerStore_UpdateRule_Call) RunAndReturn(run func(context.Context, *config.TriggerRule) error) *MockTriggerStore_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTriggerStore creates a new instance of MockTriggerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTriggerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTriggerStore {
	mock := &MockTriggerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
